### ISSUE TITLE
form code

### ISSUE THREAD

**Issue by QueenOyster** [QueenOyster/java_study#1]
こんな感じでしょうか。
960pxを境界値にしています。（960以上で2列横並び、それ以下で1列になります）

## サンプルコード
```erb
<h1>検索画面のサンプル</h1>

<%= form_with(url: movies_path, method: :get, html: {class: "search-form"}) do |form| %>
  <div class="flex-container-section">
    <div class="search-form-column">
      <div class="form-item">
        <%= form.label 'id' %>
        <%= form.number_field :id, value: params[:id] %><br>
      </div>

      <div class="form-item">
        <%= form.label 'タイトル' %>
        <%= form.text_field :title, value: params[:title] %><br>
      </div>

      <div class="form-item">
        <%= form.label '監督' %>
        <%= form.text_field :director, value: params[:director] %>
      </div>
    </div>

    <div class="search-form-column">
      <div class="form-item">
        <%= form.label '生成時刻' %>
        <%= form.datetime_local_field :created_at_start, value: params[:created_at_start] %> ~
        <%= form.datetime_local_field :created_at_finish, value: params[:created_at_finish] %><br>
      </div>

      <div class="form-item">
        <%= form.label '更新時刻' %>
        <%= form.datetime_local_field :updated_at_start, value: params[:updated_at_start] %> ~
        <%= form.datetime_local_field :updated_at_finish, value: params[:updated_at_finish] %><br>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit '検索' %>
  </div>
<% end %>
```

```css

form {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}

/* 幅960px以上は横並び */
@media (min-width: 960px) {
  .flex-container-section {
    display: flex;
  }
}

.flex-container-section .search-form-column:nth-child(1) {
  width: 320px;
}

.flex-container-section .search-form-column:nth-child(2) {
  width: 480px;
}

.form-item {
  margin: 16px 0;
}

.form-item label {
  display: inline-block;
  width: 80px;
}

.search-form .actions {
  display: flex;
  justify-content: center;
}
```

## 動画キャプチャ

https://user-images.githubusercontent.com/25859155/203075463-a505e2d7-5909-4b23-add2-799775f592d3.mov
